name: Cypress Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with: 
          start: npm start

  deploy-to-uat:
    runs-on: ubuntu-latest
    environment: uat
    needs: cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Deploy to uat
        run: |
          echo "Deploying to uat environment..."
          # Set the path to the deployment tool
          export PATH=$PATH:/path/to/my-deployment-tool
          # Install dependencies and build your project artifacts
          npm ci
          npm run build
          # Deploy your artifacts to your uat environment
          my-deployment-tool deploy --env uat --artifact ./build

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-to-uat
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Deploy to prod
        run: |
          echo "Deploying to prod environment..."
          # Set the path to the deployment tool
          export PATH=$PATH:/path/to/my-deployment-tool
          # Install dependencies and build your project artifacts
          npm ci
          npm run build
          # Deploy your artifacts to your prod environment
          my-deployment-tool deploy --env prod --artifact ./build
