name: Cypress Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with: 
          start: npm start

  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Deploy to dev
        run: |
          echo "Deploying to dev environment..."
          # Install dependencies and build your project artifacts
          npm ci
          npm run build
          # Deploy your artifacts to your dev environment
          my-deployment-tool deploy --env dev --artifact ./build

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-to-dev
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Deploy to prod
        run: |
          echo "Deploying to prod environment..."
          # Install dependencies and build your project artifacts
          npm ci
          npm run build
          # Deploy your artifacts to your prod environment
          my-deployment-tool deploy --env prod --artifact ./build
